In [1]:
import numpy as np

# array = mat_neigh
dem = np.array([[10, 20, 30, 40],[10, 20, 30, 40],[10, 20, 30, 40],[10, 20, 30, 40]])

print(dem)
s= dem.shape
print(f'\n {dem.shape}')

[[10 20 30 40]
 [10 20 30 40]
 [10 20 30 40]
 [10 20 30 40]]

 (4, 4)


In [2]:
# Create an array of 0's equal to the shape of the DEM
grid_thikn = np.zeros(s)

# Create an array of 1's equal to the shape of the DEM
grid_diff = np.ones(s)

# Create matrices to store values of neighbouring cells in the previous iteration
mat_neigh = np.zeros(s)

# Change the shape of the matrix, adding a "plane depth" to the matrix
mat_neigh = np.expand_dims(mat_neigh, axis=2)

# Assume 4-neighbor method:
# Repeat the values of the mat_neighbor creating a 4 plane depth
mat_neigh = np.tile(mat_neigh, (1,1,4))

# Create a comparison matrix
mat_comp = np.zeros(s)
mat_comp = np.expand_dims(mat_comp, axis=2)
mat_comp = np.tile(mat_comp, (1,1,2))

In [3]:
# Initiate a copy of the DEM
grid_slbl = dem.copy()

# Initialize variables before the while loop
nb_iter = 0
volume = 0

# Assume a maximum thickness of 5 FOR NOW
maxt = 7
# Assume a maximum volume of 10000
maxv = 100
# Assume a STOP criterion of 0.1
stop = 1

# Subtract the MAX THICKNESS to the DEM
grid_maxt = dem - maxt

SLBL starts

Below details what the code does:

1. 

In [4]:
# Consider a single iteration, iter = 1

# Create a copy of the grid_thckn
# grid_thikn is an array of 0's
# So grid_thikn_prev is just a 0-array at the start
grid_thikn_prev = grid_thikn.copy()

# Create a copy of the grid_slbl
# To be used as the previous iteration, at the start of the iteration
grid_slbl_prev = grid_slbl.copy()

# Assign values of the neighboring cells in the axis = 2

# copies the values prev_slbl from 2nd row to end, and all columns
# then:
# insert to mat_neigh at: all rows except the last on the 1st plane
mat_neigh[:-1,:,0]=grid_slbl_prev[1:,:]

# insert to mat_neigh at: 2nd row till en
mat_neigh[1:,:,1]=grid_slbl_prev[:-1,:]


mat_neigh[:,:-1,2]=grid_slbl_prev[:,1:]
mat_neigh[:,1:,3]=grid_slbl_prev[:,:-1]

mat_neigh

array([[[10.,  0., 20.,  0.],
        [20.,  0., 30., 10.],
        [30.,  0., 40., 20.],
        [40.,  0.,  0., 30.]],

       [[10., 10., 20.,  0.],
        [20., 20., 30., 10.],
        [30., 30., 40., 20.],
        [40., 40.,  0., 30.]],

       [[10., 10., 20.,  0.],
        [20., 20., 30., 10.],
        [30., 30., 40., 20.],
        [40., 40.,  0., 30.]],

       [[ 0., 10., 20.,  0.],
        [ 0., 20., 30., 10.],
        [ 0., 30., 40., 20.],
        [ 0., 40.,  0., 30.]]])