In [48]:
import rasterio
file_path = '/home/richmond/Downloads/LiDAR 0.5m.SNGP DTM_0.5m_04052023_51N.tif'
with rasterio.open(file_path, 'r') as src:
    s = src.shape
    mat_neigh = np.zeros(s)
    mat_neigh = np.expand_dims(mat_neigh, axis=2)

mat_neigh.shape

(12000, 16000, 1)

In [50]:
import numpy as np

array = mat_neigh
# array = np.array([10, 20, 30, 40])

# print(array)
print(f'\n {array.shape}')


 (12000, 16000, 1)


In [52]:
array_expanded = np.expand_dims(array, 2)

# print(array_expanded)
print(f'\n {array_expanded.shape}')

array_expanded = np.tile(array_expanded, (1,1,4))

print(array_expanded)
print(f'\n {array_expanded.shape}')


 (12000, 16000, 1, 1)
[[[[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  ...

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  ...

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  ...

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]]


 ...


 [[[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  ...

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  ...

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  ...

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]]]

 (12000, 16000, 1, 4)
